### ISSUE TITLE
get_hsy() is broken

### ISSUE THREAD

**Issue by ouzor** [rOpenGov/helsinki#13]
HSY open data pages have been updated, need to update get_hsy() correspondingly!

**Comment by antagomir** [comment]
I switched off the vignette example on get_hsy now as well. Should be activated when get_hsy function is fixed.

**Comment by ouzor** [comment]
I started fixing this issue in branch fix-hsy. Vaestotietoruudukko works now, but the other data types (Rakennustietoruudukko, SeutuRAMAVA) still need updating.

**Comment by antagomir** [comment]
Great, we should arrange a HELSINKI hackathon !

**Comment by ouzor** [comment]
HSY open data offering has changed a lot again since the last attempt to update things, so need to rethink this. The earlier `fix-hsy` branch is probably useless, but let's see.

Importantly, there is a WFS API that we likely want to use. 

In addition, there are some older datasets that we might want to support, e.g. here: https://www.hsy.fi/ymparistotieto/avoindata/avoin-data---sivut/paakaupunkiseudun-vaestotietoruudukko/. For maintainability though, it would be better to just support HSY, and maybe add comment that if you want earlier files, you can find them from this URL.
