### ISSUE TITLE
CRAN Checks fail (version 1.0.3)

### ISSUE THREAD

**Issue by ouzor** [rOpenGov/helsinki#23]
CRAN Checks fail, see more here: https://cran.r-project.org/web/checks/check_results_helsinki.html. 

Should be fixed by 30.9.

**Comment by pitkant** [comment]
Fixed on b2d5f39 by making vignette parts requiring internet connection eval = FALSE on CRAN

**Comment by ouzor** [comment]
Thanks, I submitted version 1.0.4 to CRAN. Will close this when submission successful.

**Comment by ouzor** [comment]
Does not pass automatic tests:
> package helsinki_1.0.4.tar.gz does not pass the incoming checks automatically, please see the following pre-tests:
Windows: <https://win-builder.r-project.org/incoming_pretest/helsinki_1.0.4_20210925_090555/Windows/00check.log>
Status: OK
Debian: <https://win-builder.r-project.org/incoming_pretest/helsinki_1.0.4_20210925_090555/Debian/00check.log>
Status: 1 WARNING

It's the GDAL issue:
> Warning in CPL_read_ogr(dsn, layer, query, as.character(options), quiet,  :
  GDAL Error 1: Driver COUCHDB is considered for removal in GDAL 3.5. You are invited to convert any dataset in that format to another more common one .If you need this driver in future GDAL versions, create a ticket at https://github.com/OSGeo/gdal (look first for an existing one first) to explain how critical it is for you (but the GDAL project may still remove it), and to enable it now, set the GDAL_ENABLE_DEPRECATED_DRIVER_COUCHDB configuration option / environment variable to YES
Quitting from lines 176-189 (helsinki_tutorial.Rmd) 
Error: processing vignette 'helsinki_tutorial.Rmd' failed with diagnostics:
Cannot open "https://kartta.hel.fi/ws/geoserver/avoindata/wfs?service=wfs&version=1.1.0&request=GetFeature&typeName=avoindata%3ASeutukartta_aluejako_suuralue&srsName=EPSG%3A3879&outputFormat=GML2"; The file doesn't seem to exist.
--- failed re-building ‘helsinki_tutorial.Rmd’

**Comment by pitkant** [comment]
All checks now ok on CRAN. We'll take another look at COUCHDB driver if above mentioned warning persists.
