### ISSUE TITLE
get_servicemap() should fail gracefully

### ISSUE THREAD

**Issue by ouzor** [rOpenGov/helsinki#26]
Ripley emailed: 

Please see the problems shown on
<https://cran.r-project.org/web/checks/check_results_helsinki.html>.

Please correct before 2022-12-04 to safely retain your package on CRAN.

It seems we need to remind you of the CRAN policy:

'Packages which use Internet resources should fail gracefully with an informative message
if the resource is not available or has changed (and not give a check warning nor error).'

This needs correction whether or not the resource recovers.

**Comment by ouzor** [comment]
Seems the Service Map API is unreliable. I managed to reproduce the error locally, but then after a minute the query worked again. 

One thing I see that we check if `api_url` is available, but not the actual query `url`. It may be that the query fails due to timeout, and the `api_url` availability check does not catch this. 

This might be a good solution: https://community.rstudio.com/t/internet-resources-should-fail-gracefully/49199/12.

**Comment by pitkant** [comment]
It would seem we forgot to put \dontrun in the function examples and inadvertently used CRAN as our CI / testing platform. Oops. Of course the function could've also failed gracefully, we currently have a `warning()` there whereas it should be a `message()`.

The good thing about this mess is that I noticed that the API (https://api.hel.fi/servicemap/v2/) seems to be nowadays somewhat deprecated. I couldn't get the only parameter for the search query working, the API just returned the responses in an unfiltered state.

[HRI website for Helsinki metropolitan area Service Map APIs](https://hri.fi/data/en_GB/dataset/paakaupunkiseudun-palvelukartan-rest-rajapinta) lists two API URLs that we could use instead:
- REST API: https://www.hel.fi/palvelukarttaws/restpages/ver4.html
- WFS API: https://kartta.hel.fi/ws/geoserver/avoindata/wfs?request=GetCapabilities

**Comment by ouzor** [comment]
Ok great that you identified the issue!

Then about the API, I also noticed that the only-query did not affect the results, but forgot to report that. 

So I think we can either try the new API or just deprecate the function. We could keep the function but then add a message that this is deprecated, and if someone wants to contribute implementation for the new API, they are welcome. Would be nice to know if anyone is using this function.

**Comment by antagomir** [comment]
Sounds like a good plan. If none of us has immediate use for the new API, I would leave it up to contributors for now. 

Just thinking if we should open a new issue for that, so that it is a well-defined task (albeit a bigger one) for someone to pick up?

**Comment by ouzor** [comment]
Sounds good! If you make changes to the service map API, please consider updating also the linked events api, which has exactly the same implementation, and could thus fail in similar manner in the future.

**Comment by rsbivand** [comment]
You need to fix this properly, this is not about CRAN testing. 

Anyone else running reverse dependency checks will see the same apparent transient error. 

In my case running revdep checks on **sf** to see whether an update in PROJ (external library used by **sf**) - almost 1200 packages across R-spatial - I do not find packages that sometimes pass and sometimes fail because of server access at all helpful. 

For every such package, I need to cross-check the reasons for the check failure to see if any changes n the upstream software may have led to a regression.

**Comment by ouzor** [comment]
Done, new version submitted to CRAN successfully.
